;; Problem 22

(import (scheme base)
        (scheme write)
        (scheme file)
        (chibi io)
        (chibi string)
        (srfi 95))

(define (alphabeta char)
  (cond ((char=? char #\A) 1)
        ((char=? char #\B) 2)
        ((char=? char #\C) 3)
        ((char=? char #\D) 4)
        ((char=? char #\E) 5)
        ((char=? char #\F) 6)
        ((char=? char #\G) 7)
        ((char=? char #\H) 8)
        ((char=? char #\I) 9)
        ((char=? char #\J) 10)
        ((char=? char #\K) 11)
        ((char=? char #\L) 12)
        ((char=? char #\M) 13)
        ((char=? char #\N) 14)
        ((char=? char #\O) 15)
        ((char=? char #\P) 16)
        ((char=? char #\Q) 17)
        ((char=? char #\R) 18)
        ((char=? char #\S) 19)
        ((char=? char #\T) 20)
        ((char=? char #\U) 21)
        ((char=? char #\V) 22)
        ((char=? char #\W) 23)
        ((char=? char #\X) 24)
        ((char=? char #\Y) 25)
        ((char=? char #\Z) 26)))

(define (alphabetize names)
  (sort names string<?))

(define (names-scores names)
  (let loop ((names names)
             (i 1)
             (total 0))
    (if (pair? names)
        (loop (cdr names)
              (+ i 1)
              (+ total (* i (string-fold (lambda (char sum)
                                           (+ sum (alphabeta char)))
                                         0 (car names)))))
        total)))

(define names (map (lambda (str) (string-trim str #\"))
                   (string-split (file->string "022.txt") #\,)))

(display (names-scores (alphabetize names)))
(newline)
