;; Problem 2
;;
;; Each new term in the Fibonacci sequence is
;; generated by adding the previous two terms.
;; 
;; By starting with 1 and 2, the first 10 terms
;; will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci
;; sequence whose values do not exceed four
;; million, find the sum of the even-valued
;; terms.

(define (sum-of-fibonacci-to ceiling)
  (let loop ((m 1) (n 1) (sum 0))
    (define o (+ m n))
    (if (<= n ceiling)
        (loop n o (if (even? o)
                      (+ sum o)
                      sum))
        sum)))

(display (sum-of-fibonacci-to 4000000))
(exit)
